# Generated by Django 5.1.3 on 2024-12-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='author_id',
            field=models.CharField(default='nul', max_length=255),
        ),
    ]
